# Shared command-line development environment for macOS.
brew "chezmoi"
brew "git"
brew "gh"
brew "jq"
brew "ripgrep"
brew "fd"
brew "fzf"
brew "zoxide"
brew "eza"
brew "tree"
brew "neovim"
brew "lazygit"
brew "btop"
brew "fastfetch"
brew "node"
brew "python@3.14"
brew "pipx"
